a=input("Ho va ten: ")
b=int(input("So ngay cong: "))
c=int(input("Don gia ngay cong: "))
d=float(input("He so phu cap: "))
e=int(input("Tam ung: "))
N=(b*c*d)
T=(N-e)
print("Nhan vien " + str(a) + ", Co tien Luong=" + str(N) + ", Tam ung=" + str(e) + " va Thuc linh=" + str(T))
